spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo_db
    username: todo_user
    password: todo_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

server:
  port: 8080
